<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Evaluator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Reference to target code containing bug examples -->
    <ProjectReference Include="../TargetCode/TargetCode.csproj" />

    <!-- Dependencies -->
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
